### ISSUE TITLE
Cannot run tests with new Codecept.loadTests glob implementation

### ISSUE THREAD

**Issue by akrueger** [Codeception/CodeceptJS#1018]
#### What are you trying to achieve?
Run tests

#### What do you get instead?
`Error: Cannot find module`

It's looking for my tests in the wrong path

#### Explanation

I'm using `codecept.conf.js` and passing the config directly in: 
`codeceptjs run --config ./client/src/test/e2e`

My `config.tests`:
`./tests/**/*.test.js`

This works in `1.1.6`, but breaks in `1.1.7`.

In `loadTests(pattern)` of `codecept.js`, I get the following:

```
PATTERN:
./tests/**/*.test.js

GLOBAL CODECEPT DIR: 
<ABSOLUTE PATH TO PROJECT>/client/src/test/e2e:

GLOB: 
./tests/changePassword.test.js,
./tests/changeSecurityQuestions.test.js,
./tests/createAccount.test.js,
./tests/login.test.js,./tests/logout.test.js,
./tests/submitApplication.test.js,
./tests/updateProfile.test.js:

TEST FILES: 
<ABSOLUTE PATH TO PROJECT>/tests/changePassword.test.js,
<ABSOLUTE PATH TO PROJECT>/tests/changeSecurityQuestions.test.js,
<ABSOLUTE PATH TO PROJECT>/tests/createAccount.test.js,
<ABSOLUTE PATH TO PROJECT>/tests/login.test.js,
<ABSOLUTE PATH TO PROJECT>/tests/logout.test.js,
<ABSOLUTE PATH TO PROJECT>/tests/submitApplication.test.js,
<ABSOLUTE PATH TO PROJECT>/tests/updateProfile.test.js:
```

The glob doesn't seem to be allowing for the tests and config to be in different places.

The latest change to the arguments of `glob.sync()` seem responsible:
![screen shot 2018-04-05 at 13 59 12](https://user-images.githubusercontent.com/1644520/38386498-7514f6aa-38da-11e8-84af-585b016e523a.png)

### Details

* CodeceptJS version: 1.1.7
* NodeJS Version: 8.9.4
* Operating System: macOs 

Possibly related to
#1014

**Comment by sveneisenschmidt** [comment]
HI @akrueger, I am currently looking into this issue. I reverted locally the changes of `loadTests` and see still the same error. 

I also went back to 1.1.6 and still get the same error. A quick solution I found was to use relative paths for test and step files to the test root file.

**Comment by akrueger** [comment]
What file structure are you working with in your tests?

This is mine:
```
./client
├── proxy.conf.json
├── src
│   ├── app
│   │   ├── app.component.html
│   │   ├── app.component.js
│   │   ├── app.component.ts
│   │   ├── app.config.ts
│   │   ├── app.module.js
│   │   ├── app.module.ts
│   │   ├── app.routing.ts
│   │   ├── app.store.ts
│   │   ├── errors
│   │   │   ├── client-error-handler.service.ts
│   │   │   ├── client-error.model.ts
│   │   │   ├── error-logger.service.ts
│   │   │   ├── errors-effects.service.ts
│   │   │   ├── errors.actions.ts
│   │   │   └── global-error-handler.service.ts
│   │   ├── messages
│   │   │   └── messages.service.ts
│   │   ├── modules
│   │   │   ├── applications
│   │   │   ├── authentication
│   │   │   ├── misc
│   │   │   └── search
│   │   └── shared
│   │       ├── custom-encoder.service.ts
│   │       ├── number-only.directive.ts
│   │       ├── pdf
│   │       ├── platform.service.ts
│   │       ├── shared.module.ts
│   │       ├── tests
│   │       ├── ui-components
│   │       └── validatorsCustom.ts
│   ├── assets
│   │   └── images
│   │       └── seal.png
│   ├── environments
│   │   ├── environment.prod.ts
│   │   └── environment.ts
│   ├── index.html
│   ├── jestGlobalMocks.ts
│   ├── main.ts
│   ├── polyfills.ts
│   ├── setupJest.ts
│   ├── styles
│   │   └── styles.scss
│   ├── test
│   │   └── e2e
│   │       ├── NODE_ENV.js
│   │       ├── codecept.conf.js
│   │       ├── custom_steps.js
│   │       ├── output
│   │       ├── pages
│   │       ├── steps.d.ts
│   │       ├── tests
│   │       ├── utility_nightmare_helper.js
│   │       ├── utility_protractor_helper.js
│   │       └── utility_webdriver_helper.js
│   ├── test.ts
│   ├── tsconfig.app.json
│   └── tsconfig.test.json
├── tsconfig.json
└── tslint.json
```
