### ISSUE TITLE
Error: Could not load plugin wdio from module './plugin/wdio': Cannot find module './plugin/wdio'

### ISSUE THREAD

**Issue by gtycherry** [Codeception/CodeceptJS#2151]
#### What are you trying to achieve?
I tried to use codecept js with webdriver help to run visual testing
#### What do you get instead?
When ran the test with specific config file, ran into below error
![image](https://user-images.githubusercontent.com/8056464/72675966-d170fd00-3ac6-11ea-8470-3727f1ade439.png)

> Provide test source code if related
package.json as below:
![image](https://user-images.githubusercontent.com/8056464/72675945-9d95d780-3ac6-11ea-9708-f9d1120d97ad.png)
config.js as below 
![image](https://user-images.githubusercontent.com/8056464/72675996-14cb6b80-3ac7-11ea-8476-b67f85714bc9.png)

### Details

* CodeceptJS version:
* NodeJS Version: v8.11.3
* Operating System:
*  webdriverio
* Configuration file:

```js
# paste config here
```

**Comment by PeterNgTr** [comment]
@gtycherry your codeceptjs version is too old, trying to use the latest one.

**Comment by gtycherry** [comment]
@PeterNgTr thanks for recommendation, the error disappears when i upgraded codeceptjs to 2.3.6.

**Comment by hungdao-testing** [comment]
I got the same issue
Here is my configuration
```
const { setHeadlessWhen } = require("@codeceptjs/configure");

// turn on headless mode when running with HEADLESS=true environment variable
// HEADLESS=true npx codecept run
setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: "./*_test.js",
  output: "./output",
  helpers: {
    WebDriver: {
      url: "http://localhost",
      browser: "chrome",
      host: "127.0.0.1",
      port: 4444,
      restart: false,
      windowSize: "1920x1680"
    }
  },
  include: {
    I: "./steps_file.js"
  },
  bootstrap: null,
  mocha: {},
  name: "googlecalendar",
  plugins: {
    retryFailedStep: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    },
    wdio: {
      enabled: true,
      services: ["selenium-standalone"]
    }
  }
};

```
```
{
  "name": "googlecalendar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {},
  "dependencies": {
    "@wdio/selenium-standalone-service": "^6.0.4",
    "codeceptjs": "^2.5.0"
  }
}

```
Notes: already install selenium-standalone

**Comment by mohiteashishd** [comment]
Facing the issue :
Could not load plugin wdio from module './plugin/wdio':
Cannot read property 'outputDir' of undefined

"devDependencies": {
    "@wdio/cli": "^6.0.14",
    "@wdio/selenium-standalone-service": "^6.0.12",
    "codeceptjs": "^2.6.1",
    "webdriver": "^6.0.14"

**Comment by conradkirschner** [comment]
why is it closed?

**Comment by codejamninja** [comment]
Use version `5.16.10` of `@wdio/selenium-standalone-service` 

```
    "@wdio/selenium-standalone-service": "^5.16.10",
```

**Comment by x86chi** [comment]
> Use version `5.16.10` of `@wdio/selenium-standalone-service`
> 
> ```
>     "@wdio/selenium-standalone-service": "^5.16.10",
> ```

```bash
TSError: ⨯ Unable to compile TypeScript:
src/specs/e2e/main.spec.ts:1:1 - error TS2304: Cannot find name 'Feature'.

1 Feature('My First Test')
  ~~~~~~~
src/specs/e2e/main.spec.ts:3:1 - error TS2304: Cannot find name 'Scenario'.

3 Scenario('test something', I => {
  ~~~~~~~~
```

It crash on Typescript environment.

**Comment by Mayur150** [comment]
exports.config = {
  tests: '././*_test.ts',
  //output: './output',
  timeout: 10000,
  helpers: {
    WebDriver: {
      url: 'https://localhost.com/dummy',
      browser: 'chrome',
      smartWait: 5000,
      windowSize: '1920x1680',
      desiredCapabilities: {
        chromeOptions: {
          useAutomationExtension: false,
          // args: [
          //   '--headless',
          //   '--disable-gpu',
          //   '--disable-web-security',
          //   '--window-size=1200,1000',
          //   '--no-sandbox'
          // ]
        }
      }
    }
  },
  plugins: {
    wdio: {
      enabled: true,
      services: [
       ['selenium-standalone', {
          installArgs: {
            version: '3.141.59',
            baseURL: 'https://selenium-release.storage.googleapis.com',
            drivers: {
              chrome: { 
                version: '84.0.4147.30',
                baseURL: 'https://chromedriver.storage.googleapis.com'
              }
            },
            proxy: 'http://http.corporateproxy.com:port'
          },
          args: {
            drivers: {
              chrome: {
                version: '84.0.4147.30'
              }
            }
          }
        }]
      ]
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  //mocha: { },
  name: 'e2e'
}

"@wdio/cli": "^6.3.6",
    "@wdio/selenium-standalone-service": "^6.1.14",
    "codeceptjs": "^2.6.6",
"webdriverio": "^6.1.23"


Experiencing this Error : 
Could not load plugin wdio from module './plugin/wdio':
name.toLowerCase is not a function

could someone help us i resolving this

**Comment by JunNakamuta** [comment]
Hi

I got same error. and this error occurs here: 
https://github.com/codeceptjs/CodeceptJS/blob/master/lib/plugin/wdio.js#L100

I think we should modify here: 
> services: [
['selenium-standalone', {
installArgs: {

**Comment by prabhushan** [comment]
What we should modify? It still throws the error
