### ISSUE TITLE
Error processing test.finish event: TypeError: finish is not a function

### ISSUE THREAD

**Issue by incoming-th** [Codeception/CodeceptJS#5461]
Hi,

I believe this is a small fix but I can't figure it from where.

Maybe someone could help to check and guide, or even better already has a solution for this:

Error processing test.finish event:
TypeError: finish is not a function
    at EventEmitter.<anonymous> (/.../node_modules/codeceptjs/lib/pause.js:40:5)
    at EventEmitter.emit (node:events:529:35)
    at Object.emit (/.../node_modules/codeceptjs/lib/event.js:162:28)
    at /.../node_modules/codeceptjs/lib/mocha/asyncWrapper.js:74:13
    at /.../node_modules/codeceptjs/lib/recorder.js:274:9

<img width="1562" height="1392" alt="Image" src="https://github.com/user-attachments/assets/ebd5ecdb-9265-4156-b462-6adfb1bfd428" />

Can be reproduced by doing:

recorder.add(`Error`,  () => Promise.reject(new Error(message)));

Thanks!

**Comment by kobenguyent** [comment]
noticed this was introduced by https://github.com/codeceptjs/CodeceptJS/pull/4713

**Comment by kobenguyent** [comment]
@incoming-th may you try this fix locally?


Here's why:

### The Bug

`finish` is declared as a module-level variable (line 18) but is **only assigned inside `pauseSession()`** (line 86), where it's set to the `resolve` function of a `Promise`:

```javascript name=lib/pause.js url=https://github.com/codeceptjs/CodeceptJS/blob/83cb43d5fc6faf1fbbf2b9c493950e1c94059ab7/lib/pause.js#L85-L88
return new Promise(resolve => {
    finish = resolve  // ← only assigned here
    return askForStep()
})
```

### The Race Condition

The `event.test.finished` listener is registered at line 39 and calls `finish()` at line 40:

```javascript name=lib/pause.js url=https://github.com/codeceptjs/CodeceptJS/blob/83cb43d5fc6faf1fbbf2b9c493950e1c94059ab7/lib/pause.js#L39-L44
event.dispatcher.on(event.test.finished, () => {
    finish()  // ← called here
    recorder.session.restore('pause')
    rl.close()
    history.save()
})
```

This will throw `TypeError: finish is not a function` if **`event.test.finished` fires before `pauseSession()` has ever been called** — because `finish` is still `undefined` at that point.

### When Can This Happen?

- A test finishes very quickly (e.g., skipped, errored early) **before** `recorder.add('Start new session', ...)` has had a chance to invoke `pauseSession()`.
- The `pause()` function is called, the event listener is registered, but the recorder hasn't yet executed the `pauseSession` callback by the time the `test.finished` event fires.

### Fix

Guard the `finish()` call with a type check:

```javascript
event.dispatcher.on(event.test.finished, () => {
    if (typeof finish === 'function') finish()  // ← safe guard
    recorder.session.restore('pause')
    rl.close()
    history.save()
})
```

The same guard should also be applied to the `parseInput` call at **line 97**, which has the same vulnerability.

**Comment by incoming-th** [comment]
@kobenguyent Thanks for looking into this. The safeguard is fine.
