### PR TITLE
fix(cli): gherkin command init with TypeScript

### LINKED ISSUE #4350: "undefined undefined" error when bdd:init
#### What are you trying to achieve?

Since version 3.6.2 (was working in 3.6.1), when you enable gherkin/bdd, an error occurs on updating the configuration to add the gherkin part with "undefined undefined"
Reproduced on both linux & windows.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
npx codeceptjs bdd:init
```

> Output :

```js
Initializing Gherkin (Cucumber BDD) for CodeceptJS
--------------------------
Created /config/workspace/features, place your *.feature files in it
Created sample feature file: features/basic.feature
Created /config/workspace/step_definitions, place step definitions into it
Created sample steps file: step_definitions/steps.js

codecept.conf.js config can't be updated automatically
Please update it manually:

undefined: undefined

Gherkin setup is done.
Start writing feature files and implement corresponding steps.
```

### Details

```js
codeceptVersion:  "3.6.2"
nodeInfo:  14.21.3
osInfo:  Linux 6.1 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
cpuInfo:  (12) x64 AMD Ryzen 5 5600GT with Radeon Graphics
chromeInfo:  Not Found
edgeInfo:  "N/A"
firefoxInfo:  undefined
safariInfo:  N/A
```

### PR DESCRIPTION
**Pull request by andonary**
fix this command when project is initialized with TypeScript:

```
npx codeceptjs gherkin:init
```

## Motivation/Description of the PR
- Resolves #4350

Applicable helpers:

- [ ] Playwright
- [ ] Puppeteer
- [ ] WebDriver
- [ ] REST
- [ ] FileHelper
- [ ] Appium
- [ ] TestCafe

Applicable plugins:

- [ ] allure
- [ ] autoDelay
- [ ] autoLogin
- [ ] customLocator
- [ ] pauseOnFail
- [ ] coverage
- [ ] retryFailedStep
- [ ] screenshotOnFail
- [ ] selenoid
- [ ] stepByStepReport
- [ ] stepTimeout
- [ ] wdio
- [ ] subtitles

## Type of change

- [ ] :fire: Breaking changes
- [ ] :rocket: New functionality
- [x] :bug: Bug fix
- [ ] 🧹 Chore
- [ ] :clipboard: Documentation changes/updates
- [ ] :hotsprings: Hot fix
- [ ] :hammer: Markdown files fix - not related to source code
- [ ] :nail_care: Polish code

## Checklist:

- [x] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

### CODE REVIEW

File: lib/command/gherkin/init.js [hunk 1]
```diff
@@ -27,6 +27,19 @@ Given('I have a defined step', () => {
 module.exports = function (genPath) {
   const testsPath = getTestRoot(genPath);
   const config = getConfig(testsPath);
+  let extension = "js";
+  let configFile = path.join(testsPath, `codecept.conf.${extension}`);
+
+  if (!fileExists(configFile)) {
```
Comment (kobenguyent) [inline lib/command/gherkin/init.js]: what do you think if we provide a function like this?

```
function findConfigFile(testsPath) {
  const extensions = ['js', 'ts'];
  for (const ext of extensions) {
    const configFile = path.join(testsPath, `codecept.conf.${ext}`);
    if (fileExists(configFile)) {
      return configFile;
    }
  }
  return null;
}
```
then 

```
const configFile = findConfigFile(testsPath);

if (!configFile) {
  output.error(
    "Can't initialize Gherkin. This command must be run in an already initialized project."
  );
  process.exit(1);
}
```

Comment (andonary) [reply lib/command/gherkin/init.js]: why not
