### PR TITLE
fix: switchTo - within block

### LINKED ISSUE #3880: within()/I.switchTo() fails in specific case: Either name or url matcher should be specified
It works well in 3.5.3
It's related to #3846, CC: @kobenguyent 
In 3.5.4 I'm getting ` ERROR  locator.toLowerCase is not a function` and in 3.5.5 I'm getting `Either name or url matcher should be specified`
#### What are you trying to achieve?
The scenario should pass. Unfortunately I don't have a simplistic case, so I used a scenario from our production tests.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
  Teacher: Verify the kit's content
 › [Dir] /home/mirao/workspace/codeceptjs/tests/s4e
    I click #LESSON_MENU_KIT_CONTENT
  › <screenshotOnFail> Test failed, try to save a screenshot
  › Screenshot is saving to /home/mirao/workspace/codeceptjs/tests/s4e/output/Teacher__V_1695287237.failed.png
  ✖ FAILED in 2623ms
...
1) KitLesson
       Teacher: Verify the kit's content:
     Either name or url matcher should be specified
      at assert (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/playwright-core@1.37.1/node_modules/playwright-core/lib/utils/debug.js:29:21)
      at Page.frame (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/playwright-core@1.37.1/node_modules/playwright-core/lib/client/page.js:195:23)
      at Playwright.switchTo (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.5_e6w65ce3sp4lg2q5fzcoe2hnqu/node_modules/codeceptjs/lib/helper/Playwright.js:2573:32)
```

> Provide test source code if related

```ts
function verifyKitLessonGlossary() {
    within(
        {
            frame: HtmlBodyPage.iFrame, // "(//iframe)[last()]"
        },
        () => {
            I.see(glossaryName, kitContentFragment.glossaryTerm); // locate(".glossary-term")
            // Open glossary popup
            I.click(kitContentFragment.glossaryTerm);
            // Verify content of popup
            I.see(glossaryName, glossaryTermInfoFragment.glossaryTermInfo);
            I.see(glossaryText, glossaryTermInfoFragment.glossaryTermInfo);
        }
    );
}

Scenario("Teacher: Verify the kit's content", () => {
    I.click(iPlannerPage.kitView.kitContent);

    verifyKitLessonGlossary();
});
```

### Details

* CodeceptJS version: 3.5.5
* NodeJS Version: 18.15
* Operating System: Ubuntu 22.04
* Playwright 1.37.1

### LINKED ISSUE #3891: within()/I.switchTo(): Can't find text using "I.see(text)" in iframe
It's a regression. The test passes in 3.5.3 and fails in 3.5.5.

#### What are you trying to achieve?
The test should pass

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
$ codeceptjs run My_test.ts --debug
CodeceptJS v3.5.5 #StandWithUkraine
Using test root "/home/mirao/workspace/codeceptjs/tests/my"
Helpers: Playwright
Plugins: screenshotOnFail

My --
 › [Session] Starting singleton browser session
  test something
    I am on page "https://csreis.github.io/tests/cross-site-iframe.html"
    › [Browser:Error] Failed to load resource: the server responded with a status of 404 ()
    I switch to "iframe#frame1"
    I see "Initial page", "body"
    I see "Initial page"
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png
  ✖ FAILED in 481ms


-- FAILURES:

  1) My
       test something:

      expected web application to include "Initial page"
      + expected - actual

      -Cross-site iframe test Frame 1: Go cross-site (simple page) Go cross-site (complex page) Go same-site
      +Initial page
      
  
  
  Scenario Steps:
  - I.see("Initial page") at Test.<anonymous> (./My_test.ts:7:7)
  - I.see("Initial page", "body") at Test.<anonymous> (./My_test.ts:6:7)
  - I.switchTo("iframe#frame1") at Test.<anonymous> (./My_test.ts:5:7)
  - I.amOnPage("https://csreis.github.io/tests/cross-site-iframe.html") at Test.<anonymous> (./My_test.ts:4:7)
  
  Artifacts:
  - screenshot: /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png


  FAIL  | 0 passed, 1 failed   // 1s
Run with --verbose flag to see complete NodeJS stacktrace
```
It looks like the text is being searched outside the frame.
Searching using `I.see(text, element)` works well.

> Provide test source code if related

```ts
Feature("My");

Scenario("test something", ({ I }) => {
    I.amOnPage("https://csreis.github.io/tests/cross-site-iframe.html");
    I.switchTo("iframe#frame1");
    I.see("Initial page", "body");
    I.see("Initial page");
});
```

### Details

* CodeceptJS version: 3.5.5
* NodeJS Version: 18.15
* Operating System: Ubuntu 22.04
* Playwright 1.37.1
* Configuration file:

```ts
export const config: CodeceptJS.MainConfig = {
    tests: "./*_test.ts",
    output: "./output",
    helpers: {
        Playwright: {
            browser: "chromium",
            url: "http://localhost",
            show: true,
        },
    },
    name: "my",
};

```

### LINKED ISSUE #3894: within()/I.switchTo(): Context of a 2nd iframe is used though I switched to 1st iframe
It works as expected in 3.5.3 and doesn't work in 3.5.5, so it seems to be a regression in 3.5.5 (or maybe in 3.5.4)

#### What are you trying to achieve?
The test should fail, because no such text `"The iframe element"` is in the 1st iframe on the page (it's a Google ads iframe). Note the text `"The iframe element"` is in the 2nd iframe instead (in the element "h1").

This is an output from the test run in CodeceptJS 3.5.3 (expected output) :heavy_check_mark: :
```
My --
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    I switch to {xpath: (.//iframe)[position()=1]}
    I see text equals "The iframe element", "h1"
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png
  ✖ FAILED in 6583ms


-- FAILURES:

  1) My
       test something:
     Element "h1" was not found by text|CSS|XPath
      at new ElementNotFound (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.3_it6hatrurk4vupt6qhkwl6ubhy/node_modules/codeceptjs/lib/helper/errors/ElementNotFound.js:14:11)
      at assertElementExists (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.3_it6hatrurk4vupt6qhkwl6ubhy/node_modules/codeceptjs/lib/helper/Playwright.js:3291:11)
      at Playwright.proceedSee (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.3_it6hatrurk4vupt6qhkwl6ubhy/node_modules/codeceptjs/lib/helper/Playwright.js:3128:5)
  
  Scenario Steps:
  - I.seeTextEquals("The iframe element", "h1") at Test.<anonymous> (./My_test.ts:10:7)
  - I.switchTo({xpath: (.//iframe)[position()=1]}) at Test.<anonymous> (./My_test.ts:9:7)
  - I.wait(5) at Test.<anonymous> (./My_test.ts:8:7)
  - I.click("#accept-choices") at Test.<anonymous> (./My_test.ts:7:7)
  - I.amOnPage("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe") at Test.<anonymous> (./My_test.ts:4:7)
  
  Artifacts:
  - screenshot: /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png


  FAIL  | 0 passed, 1 failed   // 7s
Run with --verbose flag to see complete NodeJS stacktrace
```

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

The test in 3.5.5 passes :lady_beetle:  :
```bash
My --
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    I switch to {xpath: (.//iframe)[position()=1]}
    I see text equals "The iframe element", "h1"
  ✔ OK in 6426ms
```
I tried it also with the fix https://github.com/codeceptjs/CodeceptJS/pull/3892, but I'm getting the same result.
> Provide test source code if related

```ts
Feature("My");

Scenario("test something", ({ I }) => {
    I.amOnPage(
        "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    );
    I.click("#accept-choices");
    I.wait(5); // Wait for Google ads to be loaded
    I.switchTo(locate("iframe").at(1)); // Switch to the iframe with Google ads
    I.seeTextEquals("The iframe element", "h1");
});
```

### Details

* CodeceptJS version: 3.5.5
* NodeJS Version: 18.15
* Operating System: Ubuntu 22.04
* Playwright 1.37.1
* Configuration file:

```ts
export const config: CodeceptJS.MainConfig = {
    tests: "./*_test.ts",
    output: "./output",
    helpers: {
        Playwright: {
            browser: "chromium",
            url: "http://localhost",
            show: true,
        },
    },
    name: "my",
};
```

### PR DESCRIPTION
**Pull request by kobenguyent**
## Motivation/Description of the PR
- Resolves #3880
- Resolves #3891
- Resolves #3894 

Applicable helpers:
- [ ] Playwright

## Type of change
- [ ] :bug: Bug fix

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [ ] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by mirao** [comment]
@kobenguyent I replaced `Playwright.js` from 3.5.5 by content of `Playright.js` from the branch `CodeceptJS/fix-switchTo`
The cases from the three issues I reported work fine with your changes.

However one of my tests (using the helper Pixelmatcher methods in an iframe) is failing with the error `context.waitForSelector is not a function` (it passes in 3.5.3)
```
1) PlayDndGame
       Verify the game (stone) is not finished:
     context.waitForSelector is not a function
      at Playwright.waitForVisible (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.5_e6w65ce3sp4lg2q5fzcoe2hnqu/node_modules/codeceptjs/lib/helper/Playwright.js:2384:28)
      at async PixelmatchHelper._takeElementScreenshot (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs-pixelmatchhelper@1.0.6_6hq34cvqihrbyrcnb4yjxphwgm/node_modules/codeceptjs-pixelmatchhelper/index.js:423:3)
      at async PixelmatchHelper.takeScreenshot (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs-pixelmatchhelper@1.0.6_6hq34cvqihrbyrcnb4yjxphwgm/node_modules/codeceptjs-pixelmatchhelper/index.js:398:4)
  
  Scenario Steps:
  - I.checkVisualDifferences("Lesson_Path_Initial_chromium_headless", ".konvajs-content", 0.001) at verifyArea (/home/mirao/workspace/codeceptjs/tests/fragments/Konvajs.ts:15:7)
```

The scenario is
```ts
Scenario("Verify the game (stone) is not finished", () => {
    within(
        {
            frame: HtmlBodyPage.iFrame, // "(//iframe)[last()]"
        },
        () => {
            konvajsFragment.verifyLessonPathArea("Lesson_Path_Initial");
        }
    );
});
```

**Comment by mirao** [comment]
> However one of my tests (using the helper Pixelmatcher methods in an iframe)

It looks like a different issue than the original ones. However it's related to `within()` (or maybe to iframe) because when I use other test using `PixelmatchHelper.takeScreenshot` and not using iframe, it works fine. 
I'll try to create a simple test case how to reproduce on a public page.

**Comment by kobenguyent** [comment]
my simple test looked good! Not sure if you have any special setup. 🤔 

```
Scenario.only('visual test',
    async ({I}) => {
        I.amOnPage('http://127.0.0.1:8000/iframe')
        within({frame: '(//iframe)[last()]'}, async () => {
            I.waitForVisible('h3', 5);
            await I.takeScreenshot("screenshot.png");
            await I.checkVisualDifferences("screenshot.png");
            const result = await I.getVisualDifferences("screenshot.png");
        });
    });
    
```

```
***************************************
CodeceptJS v3.5.5 #StandWithUkraine
Using test root "/Users/t/Downloads/highlight_error_sample"
Helpers: Playwright, PixelmatchHelper
Plugins: screenshotOnFail, tryTo

regression --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  visual test
    I am on page "http://127.0.0.1:8000/iframe"
    › [Browser:Error] Failed to load resource: the server responded with a status of 404 (Not Found)
    Within "{"frame":"(//iframe)[last()]"}" ""
      I wait for visible "h3", 5
      I take screenshot "screenshot.png"
      › Screenshot is saving to /Users/t/Downloads/highlight_error_sample/output/~4f1rp.temp.png
      I check visual differences "screenshot.png"
      › Check differences in screenshot.png ...
      › Load image from /Users/t/Downloads/highlight_error_sample/output/screenshot.png ...
      › Load image from /Users/t/Downloads/highlight_error_sample/tests/screenshots/base/screenshot.png ...
      › Difference: 0% | 0 / 921600 pixels
      I get visual differences "screenshot.png"
      › Check differences in screenshot.png ...
      › Load image from /Users/t/Downloads/highlight_error_sample/output/screenshot.png ...
      › Load image from /Users/t/Downloads/highlight_error_sample/tests/screenshots/base/screenshot.png ...
  ✔ OK in 523ms


  OK  | 1 passed   // 2s
```

**Comment by mirao** [comment]
@kobenguyent This test passes in 3.5.3 and 3.5.5, but doesn't pass in the branch `CodeceptJS/fix-switchTo`. So it seems to be broken by your latest changes in `CodeceptJS/fix-switchTo`.
It can be reproduced with `I.takeScreenshot()` if you pass an element you want to screenshot.

Config:
```ts
export const config: CodeceptJS.MainConfig = {
    tests: "./*_test.ts",
    output: "./output",
    helpers: {
        Playwright: {
            browser: "chromium",
            url: "http://localhost",
            show: true,
        },
        PixelmatchHelper: {
            require: "codeceptjs-pixelmatchhelper",
            dirExpected: "./screenshots/base/",
            dirDiff: "./screenshots/diff/",
        },
    },
    name: "my",
};

```
Test:
```ts
Feature("My");

Scenario("test something", ({ I }) => {
    I.amOnPage(
        "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    );
    I.click("#accept-choices");
    I.wait(5); // Wait for Google ads to be loaded
    within(
        {
            frame: "iframe#iframeResult",
        },
        () => {
            I.takeScreenshot("screenshot.png", "actual", "h1");
        }
    );
});

```
Output:
```
$ codeceptjs run --debug
CodeceptJS v3.5.5 #StandWithUkraine
Using test root "/home/mirao/workspace/codeceptjs/tests/my"
Helpers: Playwright, PixelmatchHelper
Plugins: screenshotOnFail

My --
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    › [Browser:Error] Failed to load resource: the server responded with a status of 400 (Bad Request)
    › [Browser:TimeEnd] a: 0.006103515625 msa: 0.006103515625 ms
    Within "{"frame":"iframe#iframeResult"}" ""
      I take screenshot "screenshot.png", "actual", "h1"
      › [Browser:Error] Failed to load resource: the server responded with a status of 400 (Bad Request)
      › [Browser:Error] Failed to load resource: the server responded with a status of 400 ()
  › <screenshotOnFail> Test failed, try to save a screenshot
  › Screenshot is saving to /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png
  ✖ FAILED in 12032ms


-- FAILURES:

  1) My
       test something:
     context.waitForSelector is not a function
      at Playwright.waitForVisible (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs@3.5.5_e6w65ce3sp4lg2q5fzcoe2hnqu/node_modules/codeceptjs/lib/helper/Playwright.js:2384:28)
      at async PixelmatchHelper._takeElementScreenshot (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs-pixelmatchhelper@1.0.6_6hq34cvqihrbyrcnb4yjxphwgm/node_modules/codeceptjs-pixelmatchhelper/index.js:423:3)
      at async PixelmatchHelper.takeScreenshot (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/codeceptjs-pixelmatchhelper@1.0.6_6hq34cvqihrbyrcnb4yjxphwgm/node_modules/codeceptjs-pixelmatchhelper/index.js:398:4)
  
  Scenario Steps:
  - I.takeScreenshot("screenshot.png", "actual", "h1") at ./My_test.ts:14:15
  - I.wait(5) at Test.<anonymous> (./My_test.ts:8:7)
  - I.click("#accept-choices") at Test.<anonymous> (./My_test.ts:7:7)
  - I.amOnPage("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe") at Test.<anonymous> (./My_test.ts:4:7)
  
  Artifacts:
  - screenshot: /home/mirao/workspace/codeceptjs/tests/my/output/test_something.failed.png


  FAIL  | 0 passed, 1 failed   // 13s
```

**Comment by kobenguyent** [comment]
May you check your code to see if you are using the correct branch?

```
CodeceptJS v3.5.5 #StandWithUkraine
Using test root "/Users/t/Downloads/highlight_error_sample"
Helpers: Playwright, PixelmatchHelper
Plugins: screenshotOnFail, tryTo

My --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    › [Browser:Error] Failed to load resource: the server responded with a status of 400 (Bad Request)
    Within "{"frame":"iframe#iframeResult"}" ""
      I take screenshot "screenshot.png", "actual", "h1"
  ✔ OK in 6154ms


  OK  | 1 passed   // 9s
```

**Comment by mirao** [comment]
@kobenguyent Maybe it's a deployment issue on my side. I copied "Playwright.js" from current `3.x` (with all your changes) to my project (with CodeceptJS 3.5.5) and the test is still failing (`context.waitForSelector is not a function`)
How do you test it in your environment?

**Comment by kobenguyent** [comment]
"codeceptjs": "github:codeceptjs/codeceptjs#fix-switchTo",

I installed the branch directly.

**Comment by mirao** [comment]
Tried again, with latest "3.x" in a fork of the repo `codeceptjs/CodeceptJS`.
I created the test directly in that project (in "~/workspace/CodeceptJS/test/my"). But still I'm getting `context.waitForSelector is not a function`.
When I switch my repo to the commit https://github.com/codeceptjs/CodeceptJS/commit/206d1dfef01488aba58dc24f5c5e84fefd93261e, the test passes.
Yes, still it could be an issue in my forked repo or some misconfiguration, it's hard to say. Maybe I could test it correctly if you released the version as a some beta version or something like that.

**Comment by kobenguyent** [comment]
Perhaps your issue would be fixed with this https://github.com/codeceptjs/CodeceptJS/pull/3918

**Comment by BenjaminHoch-GoTo** [comment]
could you please let me know, in which version this fix will be included? We are pinned to 3.5.3 because of this. 3.5.6?

**Comment by kobenguyent** [comment]
hey @BenjaminHoch-GoTo sorry for the confusion! 
so if you use **switchTo/Within** and there is no waitForVisible/waitForInvisible/waitToHide inside that block, you could try **3.5.6**, otherwise this would fix that issue but waiting for next release unfortunately https://github.com/codeceptjs/CodeceptJS/pull/3918

**Comment by BenjaminHoch-GoTo** [comment]
Yeah i just tried out 3.5.6 and still get "context.waitForSelector is not a function" . We'll wait then.

**Comment by mirao** [comment]
> Perhaps your issue would be fixed with this https://github.com/codeceptjs/CodeceptJS/pull/3918

Yes, just tried my production test that originally failed on `context.waitForSelector is not a function` in 3.5.6.
It passes with the changes from https://github.com/codeceptjs/CodeceptJS/pull/3918 :heavy_check_mark: 
**But** I noticed that now the test takes quite long time. It seems that the action `I take screenshot "screenshot.png", "actual", "h1"` is now waiting for `waitForTimeout` always. So e.g. in our project it means additional 30 sec for every `I.takeScreenshot("picture", "actual", "element")` which is annoying.
It's fast with 3.5.3

This is how the simple test looks with 20 sec. timeout:
```ts
My --
    [1]  Starting recording promises
    Timeouts: 
 › [Session] Starting singleton browser session
  test something
    I am on page "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe"
    I click "#accept-choices"
    I wait 5
    › [Browser:Error] Failed to load resource: the server responded with a status of 400 (Bad Request)
    › [Browser:Error] %cAdConsent display: inline-block; color: #fff; background: #ff0000; padding: 1px 4px; border-radius: 3px; ERROR: Unknown __tcfapi() API call 'getInAppTCData'%cAdConsent display: inline-block; color: #fff; background: #ff0000; padding: 1px 4px; border-radius: 3px; ERROR: Unknown __tcfapi() API call 'getInAppTCData'
    Within "{"frame":"iframe#iframeResult"}" ""
      I take screenshot "screenshot.png", "actual", "h1"
      › [Browser:Error] Failed to load resource: the server responded with a status of 400 (Bad Request)
  ✔ OK in 26648ms


  OK  | 1 passed   // 28s
```

**Comment by kobenguyent** [comment]
please recheck https://github.com/codeceptjs/CodeceptJS/pull/3918 if you have some time @mirao pushed some fixes for the waiting mechanism. Thank you!

**Comment by mirao** [comment]
@kobenguyent Looks good, it works well as with 3.5.3. Thanks!

**Comment by mirao** [comment]
> But I noticed that now the test takes quite long time. It seems that the action I take screenshot "screenshot.png", "actual", "h1" is now waiting for waitForTimeout always

I have suspicion that `I.waitForText()` has the same bug. I'm testing now CodeceptJS 3.5.7 and `I.waitForText("mytext")` waits for 60 sec (my value in `waitForTimeout`) though text is already found.
I'm going to create an issue for it.

**Comment by kobenguyent** [comment]
I guess this covers your issue. https://github.com/codeceptjs/CodeceptJS/pull/3984

**Comment by mirao** [comment]
@kobenguyent Confirmed. It fixes my issue, thanks.
