### ISSUE TITLE
Unable to click any button - Error matcher.$x is not a function 

### ISSUE THREAD

**Issue by nghiado** [Codeception/CodeceptJS#900]
#### What are you trying to achieve?

Click a button using its text as selector

`<button _ngcontent-c8="" class="btn btn-sm">Add Report</button>
I.click('Add Report')`
#### What do you get instead?
matcher.$x is not a function

### Details

* CodeceptJS version: 1.1.0 (codeceptjs-puppeteer)
* NodeJS Version: v8.9.4
* Operating System: macOS Sierra 10.12.16
* Puppeter

**Comment by reubenmiller** [comment]
Make sure that you have at least puppeteer 1.0.0, because the `.x$` function was only added in Puppeter v1.0.0.

**Comment by nghiado** [comment]
Thanks, it works with puppeteer 1.0.0. Maybe we need to update codeceptjs-puppeteer to grab the latest of puppeteer. It's fixed to 0.13 right now.

**Comment by reubenmiller** [comment]
@DavertMik Can you please update the puppeteer meta package to Codeceptjs 1.1.2 and Puppeteer 1.0.0?

I'll have a think about how to integrate the updating of the meta packages within the codeceptjs build process so that they are always in sync.

**Comment by DavertMik** [comment]
Looks like meta packages was not the best idea. 
Please install the codeceptjs and puppeteer separately and I think they will be played nicely together
