### ISSUE TITLE
 "undefined undefined" error when bdd:init

### ISSUE THREAD

**Issue by julien-binard** [Codeception/CodeceptJS#4350]
#### What are you trying to achieve?

Since version 3.6.2 (was working in 3.6.1), when you enable gherkin/bdd, an error occurs on updating the configuration to add the gherkin part with "undefined undefined"
Reproduced on both linux & windows.

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
npx codeceptjs bdd:init
```

> Output :

```js
Initializing Gherkin (Cucumber BDD) for CodeceptJS
--------------------------
Created /config/workspace/features, place your *.feature files in it
Created sample feature file: features/basic.feature
Created /config/workspace/step_definitions, place step definitions into it
Created sample steps file: step_definitions/steps.js

codecept.conf.js config can't be updated automatically
Please update it manually:

undefined: undefined

Gherkin setup is done.
Start writing feature files and implement corresponding steps.
```

### Details

```js
codeceptVersion:  "3.6.2"
nodeInfo:  14.21.3
osInfo:  Linux 6.1 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
cpuInfo:  (12) x64 AMD Ryzen 5 5600GT with Radeon Graphics
chromeInfo:  Not Found
edgeInfo:  "N/A"
firefoxInfo:  undefined
safariInfo:  N/A
```

**Comment by julien-binard** [comment]
Just looked at code, Project have TypeScript enabled, and looks like js/ts extension is not manager between lib gherkin:init & updateConfig
I created by mistake codecept project in TS but that explain my issue, not version update
