### ISSUE TITLE
els[0]._scrollIntoViewIfNeeded while upgrading Puppeteer version from 10.2.0 to 15.4.0

### ISSUE THREAD

**Issue by snehabhandge** [Codeception/CodeceptJS#3370]
#### What are you trying to achieve?

Upgrade Puppeteer version from 10.2.0 to 15.4.0

#### What do you get instead?

TypeError: els[0]._scrollIntoViewIfNeeded is not a function

> Provide console output if related. Use `--verbose` mode for more details.

TypeError: els[0]._scrollIntoViewIfNeeded is not a function
    at PuppeteerHelper.scrollTo (..\node_modules\codeceptjs\lib\helper\Puppeteer.js:752:20)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PuppeteerHelper.scrollToElement 

```bash
# paste output here
```

> Provide test source code if related

```js
// paste test
```

### Details

* CodeceptJS version: 3.3.4
* NodeJS Version: 14
* Operating System: Windows
* puppeteer || webdriverio || testcafe version (if related) : Puppeteer version : 15.4.0
* Configuration file: package.json

  "dependencies": {
        "codeceptjs": "^3.3.4",
        <project related dependencies>
    },
    "devDependencies": {
        "puppeteer": "^15.4.0",
        <project related dependencies>
    }

```js
# paste config here
```

**Comment by kobenguyent** [comment]
Spending some time to debug the puppeteer helper and found out since puppeteer@14.4.0 breaks the Puppeteer helper
```
tamara-thanh@Thanh-Tamara-MBP14 codeceptjs-playground % npm i puppeteer@14.4.0 --save-dev

> puppeteer@14.4.0 install /Users/tamara-thanh/Desktop/codeceptjs-playground/node_modules/puppeteer
> node install.js

Downloading Chromium r1002410 - 118.3 Mb [====================] 100% 0.0s 
Chromium (1002410) downloaded to /Users/tamara-thanh/Desktop/codeceptjs-playground/node_modules/puppeteer/.local-chromium/mac-1002410
npm WARN saveError ENOENT: no such file or directory, open '/Users/tamara-thanh/Desktop/codeceptjs-playground/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/tamara-thanh/Desktop/codeceptjs-playground/package.json'
npm WARN codeceptjs@3.3.4 requires a peer of @faker-js/faker@^5.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN codeceptjs-playground No description
npm WARN codeceptjs-playground No repository field.
npm WARN codeceptjs-playground No README data
npm WARN codeceptjs-playground No license field.

+ puppeteer@14.4.0
updated 1 package and audited 528 packages in 14.782s

62 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

tamara-thanh@Thanh-Tamara-MBP14 codeceptjs-playground % c
CodeceptJS v3.3.4 #StandWithUkraine
Using test root "/Users/tamara-thanh/Desktop/codeceptjs-playground"
Helpers: Puppeteer
Plugins: screenshotOnFail, tryTo, retryTo, eachElement

login --
    [1]  Starting recording promises
    Timeouts: 
  test something
ElementHandle {}
    I am on page "https://www.google.com"
    › [Url] https://www.google.com/
    › [Browser:Info] 
    I scroll to "button"
    [1] Error | TypeError: els[0]._scrollIntoViewIfNeeded is not a function
    [1] Error | TypeError: els[0]._scrollIntoViewIfNeeded is not a function
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /Users/tamara-thanh/Desktop/codeceptjs-playground/output/test_something.failed.png
  ✖ FAILED in 2998ms

    [2]  Starting recording promises

-- FAILURES:

  1) login
       test something:
     els[0]._scrollIntoViewIfNeeded is not a function
      at Puppeteer.scrollTo (node_modules/codeceptjs/lib/helper/Puppeteer.js:753:20)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
  
  Scenario Steps:
  - I.scrollTo("button") at Test.<anonymous> (./login_test.js:5:7)
  - I.amOnPage("https://www.google.com") at Test.<anonymous> (./login_test.js:4:7)
  
  Artifacts:
  - screenshot: /Users/tamara-thanh/Desktop/codeceptjs-playground/output/test_something.failed.png


  FAIL  | 0 passed, 1 failed   // 20s

```

It's still working fine with puppeteer@14.3.0 and backwards

```
tamara-thanh@Thanh-Tamara-MBP14 codeceptjs-playground % npm i puppeteer@14.3 --save-dev

> puppeteer@14.3.0 install /Users/tamara-thanh/Desktop/codeceptjs-playground/node_modules/puppeteer
> node install.js

Downloading Chromium r1002410 - 118.3 Mb [====================] 100% 0.0s 
Chromium (1002410) downloaded to /Users/tamara-thanh/Desktop/codeceptjs-playground/node_modules/puppeteer/.local-chromium/mac-1002410
npm WARN saveError ENOENT: no such file or directory, open '/Users/tamara-thanh/Desktop/codeceptjs-playground/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/tamara-thanh/Desktop/codeceptjs-playground/package.json'
npm WARN codeceptjs@3.3.4 requires a peer of @faker-js/faker@^5.5.3 but none is installed. You must install peer dependencies yourself.
npm WARN codeceptjs-playground No description
npm WARN codeceptjs-playground No repository field.
npm WARN codeceptjs-playground No README data
npm WARN codeceptjs-playground No license field.

+ puppeteer@14.3.0
updated 3 packages and audited 528 packages in 13.627s

62 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

tamara-thanh@Thanh-Tamara-MBP14 codeceptjs-playground % c                              
CodeceptJS v3.3.4 #StandWithUkraine
Using test root "/Users/tamara-thanh/Desktop/codeceptjs-playground"
Helpers: Puppeteer
Plugins: screenshotOnFail, tryTo, retryTo, eachElement

login --
    [1]  Starting recording promises
    Timeouts: 
  test something
ElementHandle {
  _disposed: false,
  _context: ExecutionContext {
    _client: CDPSession {
      eventsMap: [Map],
      emitter: [Object],
      _callbacks: Map(0) {},
      _connection: [Connection],
      _targetType: 'page',
      _sessionId: 'E1BCB49782E3A460E233D575B57A3DF6'
    },
    _world: DOMWorld {
      _documentPromise: [Promise],
      _contextPromise: [Promise],
      _contextResolveCallback: null,
      _detached: false,
      _waitTasks: Set(0) {},
      _boundFunctions: Map(0) {},
      _ctxBindings: Set(0) {},
      _settingUpBinding: null,
      _client: [CDPSession],
      _frameManager: [FrameManager],
      _frame: [Frame],
      _timeoutSettings: [TimeoutSettings],
      _onBindingCalled: [Function: bound _onBindingCalled] AsyncFunction
    },
    _contextId: 1,
    _contextName: ''
  },
  _client: CDPSession {
    eventsMap: Map(30) {
      'Fetch.requestPaused' => [Array],
      'Fetch.authRequired' => [Array],
      'Network.requestWillBeSent' => [Array],
      'Network.requestServedFromCache' => [Array],
      'Network.responseReceived' => [Array],
      'Network.loadingFinished' => [Array],
      'Network.loadingFailed' => [Array],
      'Network.responseReceivedExtraInfo' => [Array],
      'Page.frameAttached' => [Array],
      'Page.frameNavigated' => [Array],
      'Page.navigatedWithinDocument' => [Array],
      'Page.frameDetached' => [Array],
      'Page.frameStartedLoading' => [Array],
      'Page.frameStoppedLoading' => [Array],
      'Runtime.executionContextCreated' => [Array],
      'Runtime.executionContextDestroyed' => [Array],
      'Runtime.executionContextsCleared' => [Array],
      'Page.lifecycleEvent' => [Array],
      'Target.attachedToTarget' => [Array],
      'Target.detachedFromTarget' => [Array],
      'Page.domContentEventFired' => [Array],
      'Page.loadEventFired' => [Array],
      'Runtime.consoleAPICalled' => [Array],
      'Runtime.bindingCalled' => [Array],
      'Page.javascriptDialogOpening' => [Array],
      'Runtime.exceptionThrown' => [Array],
      'Inspector.targetCrashed' => [Array],
      'Performance.metrics' => [Array],
      'Log.entryAdded' => [Array],
      'Page.fileChooserOpened' => [Array]
    },
    emitter: {
      all: [Map],
      on: [Function: on],
      off: [Function: off],
      emit: [Function: emit]
    },
    _callbacks: Map(0) {},
    _connection: Connection {
      eventsMap: [Map],
      emitter: [Object],
      _lastId: 18,
      _sessions: [Map],
      _closed: false,
      _callbacks: Map(0) {},
      _url: 'ws://127.0.0.1:51318/devtools/browser/52604230-61f8-4c6f-8227-c76c3b37671b',
      _delay: 0,
      _transport: [NodeWebSocketTransport]
    },
    _targetType: 'page',
    _sessionId: 'E1BCB49782E3A460E233D575B57A3DF6'
  },
  _remoteObject: {
    type: 'object',
    subtype: 'node',
    className: 'HTMLBodyElement',
    description: 'body',
    objectId: '6348035631192183421.1.2'
  },
  _frame: <ref *1> Frame {
    _url: 'about:blank',
    _detached: false,
    _loaderId: '',
    _hasStartedLoading: false,
    _lifecycleEvents: Set(5) {
      'commit',
      'DOMContentLoaded',
      'load',
      'networkAlmostIdle',
      'networkIdle'
    },
    _frameManager: FrameManager {
      eventsMap: [Map],
      emitter: [Object],
      _frames: [Map],
      _contextIdToContext: [Map],
      _isolatedWorlds: [Set],
      _client: [CDPSession],
      _page: [Page],
      _networkManager: [NetworkManager],
      _timeoutSettings: [TimeoutSettings],
      _mainFrame: [Circular *1]
    },
    _parentFrame: null,
    _id: '5EEDF043D9127E1C6685C6AA79A80A73',
    _childFrames: Set(0) {},
    _client: CDPSession {
      eventsMap: [Map],
      emitter: [Object],
      _callbacks: Map(0) {},
      _connection: [Connection],
      _targetType: 'page',
      _sessionId: 'E1BCB49782E3A460E233D575B57A3DF6'
    },
    _mainWorld: DOMWorld {
      _documentPromise: [Promise],
      _contextPromise: [Promise],
      _contextResolveCallback: null,
      _detached: false,
      _waitTasks: Set(0) {},
      _boundFunctions: Map(0) {},
      _ctxBindings: Set(0) {},
      _settingUpBinding: null,
      _client: [CDPSession],
      _frameManager: [FrameManager],
      _frame: [Circular *1],
      _timeoutSettings: [TimeoutSettings],
      _onBindingCalled: [Function: bound _onBindingCalled] AsyncFunction
    },
    _secondaryWorld: DOMWorld {
      _documentPromise: null,
      _contextPromise: [Promise],
      _contextResolveCallback: null,
      _detached: false,
      _waitTasks: Set(0) {},
      _boundFunctions: Map(0) {},
      _ctxBindings: Set(0) {},
      _settingUpBinding: null,
      _client: [CDPSession],
      _frameManager: [FrameManager],
      _frame: [Circular *1],
      _timeoutSettings: [TimeoutSettings],
      _onBindingCalled: [Function: bound _onBindingCalled] AsyncFunction
    },
    _name: undefined
  },
  _page: <ref *2> Page {
    eventsMap: Map(4) {
      'load' => [Array],
      'console' => [Array],
      'dialog' => [Array],
      'error' => [Array]
    },
    emitter: {
      all: [Map],
      on: [Function: on],
      off: [Function: off],
      emit: [Function: emit]
    },
    _closed: false,
    _timeoutSettings: TimeoutSettings {
      _defaultTimeout: null,
      _defaultNavigationTimeout: 30000
    },
    _pageBindings: Map(0) {},
    _javascriptEnabled: true,
    _workers: Map(0) {},
    _fileChooserInterceptors: Set(0) {},
    _userDragInterceptionEnabled: false,
    _handlerMap: WeakMap { <items unknown> },
    _client: CDPSession {
      eventsMap: [Map],
      emitter: [Object],
      _callbacks: Map(0) {},
      _connection: [Connection],
      _targetType: 'page',
      _sessionId: 'E1BCB49782E3A460E233D575B57A3DF6'
    },
    _target: Target {
      _targetInfo: [Object],
      _browserContext: [BrowserContext],
      _targetId: '5EEDF043D9127E1C6685C6AA79A80A73',
      _sessionFactory: [Function (anonymous)],
      _ignoreHTTPSErrors: false,
      _defaultViewport: [Object],
      _screenshotTaskQueue: [TaskQueue],
      _isPageTargetCallback: [Function (anonymous)],
      _initializedCallback: [Function (anonymous)],
      _initializedPromise: [Promise],
      _closedCallback: [Function (anonymous)],
      _isClosedPromise: [Promise],
      _isInitialized: true,
      _pagePromise: [Promise]
    },
    _keyboard: Keyboard {
      _modifiers: 0,
      _pressedKeys: Set(0) {},
      _client: [CDPSession]
    },
    _mouse: Mouse {
      _x: 0,
      _y: 0,
      _button: 'none',
      _client: [CDPSession],
      _keyboard: [Keyboard]
    },
    _touchscreen: Touchscreen { _client: [CDPSession], _keyboard: [Keyboard] },
    _accessibility: Accessibility { _client: [CDPSession] },
    _frameManager: FrameManager {
      eventsMap: [Map],
      emitter: [Object],
      _frames: [Map],
      _contextIdToContext: [Map],
      _isolatedWorlds: [Set],
      _client: [CDPSession],
      _page: [Circular *2],
      _networkManager: [NetworkManager],
      _timeoutSettings: [TimeoutSettings],
      _mainFrame: [Frame]
    },
    _emulationManager: EmulationManager {
      _emulatingMobile: false,
      _hasTouch: false,
      _client: [CDPSession]
    },
    _tracing: Tracing { _recording: false, _client: [CDPSession] },
    _coverage: Coverage { _jsCoverage: [JSCoverage], _cssCoverage: [CSSCoverage] },
    _screenshotTaskQueue: TaskQueue { _chain: [Promise] },
    _viewport: { width: 1200, height: 900 }
  },
  _frameManager: <ref *3> FrameManager {
    eventsMap: Map(3) {
      Symbol(FrameManager.FrameAttached) => [Array],
      Symbol(FrameManager.FrameDetached) => [Array],
      Symbol(FrameManager.FrameNavigated) => [Array]
    },
    emitter: {
      all: [Map],
      on: [Function: on],
      off: [Function: off],
      emit: [Function: emit]
    },
    _frames: Map(1) { '5EEDF043D9127E1C6685C6AA79A80A73' => [Frame] },
    _contextIdToContext: Map(2) {
      'E1BCB49782E3A460E233D575B57A3DF6:1' => [ExecutionContext],
      'E1BCB49782E3A460E233D575B57A3DF6:2' => [ExecutionContext]
    },
    _isolatedWorlds: Set(1) {
      'E1BCB49782E3A460E233D575B57A3DF6:__puppeteer_utility_world__'
    },
    _client: CDPSession {
      eventsMap: [Map],
      emitter: [Object],
      _callbacks: Map(0) {},
      _connection: [Connection],
      _targetType: 'page',
      _sessionId: 'E1BCB49782E3A460E233D575B57A3DF6'
    },
    _page: <ref *2> Page {
      eventsMap: [Map],
      emitter: [Object],
      _closed: false,
      _timeoutSettings: [TimeoutSettings],
      _pageBindings: Map(0) {},
      _javascriptEnabled: true,
      _workers: Map(0) {},
      _fileChooserInterceptors: Set(0) {},
      _userDragInterceptionEnabled: false,
      _handlerMap: [WeakMap],
      _client: [CDPSession],
      _target: [Target],
      _keyboard: [Keyboard],
      _mouse: [Mouse],
      _touchscreen: [Touchscreen],
      _accessibility: [Accessibility],
      _frameManager: [Circular *3],
      _emulationManager: [EmulationManager],
      _tracing: [Tracing],
      _coverage: [Coverage],
      _screenshotTaskQueue: [TaskQueue],
      _viewport: [Object]
    },
    _networkManager: NetworkManager {
      eventsMap: [Map],
      emitter: [Object],
      _networkEventManager: [NetworkEventManager],
      _extraHTTPHeaders: {},
      _attemptedAuthentications: Set(0) {},
      _userRequestInterceptionEnabled: false,
      _protocolRequestInterceptionEnabled: false,
      _userCacheDisabled: false,
      _emulatedNetworkConditions: [Object],
      _client: [CDPSession],
      _ignoreHTTPSErrors: false,
      _frameManager: [Circular *3]
    },
    _timeoutSettings: TimeoutSettings {
      _defaultTimeout: null,
      _defaultNavigationTimeout: 30000
    },
    _mainFrame: <ref *1> Frame {
      _url: 'about:blank',
      _detached: false,
      _loaderId: '',
      _hasStartedLoading: false,
      _lifecycleEvents: [Set],
      _frameManager: [Circular *3],
      _parentFrame: null,
      _id: '5EEDF043D9127E1C6685C6AA79A80A73',
      _childFrames: Set(0) {},
      _client: [CDPSession],
      _mainWorld: [DOMWorld],
      _secondaryWorld: [DOMWorld],
      _name: undefined
    }
  }
}
    I am on page "https://www.google.com"
    › [Url] https://www.google.com/
    I scroll to "button"
  ✔ OK in 2714ms


  OK  | 1 passed   // 21s

```

As you can read from this `console.log(await this.page.$('body'));`
from puppeteer@14.4.0 it just returns `ElementHandle {}`

**Comment by kobenguyent** [comment]
btw, I filed an issue with puppeteer team, let's see https://github.com/puppeteer/puppeteer/issues/8687

**Comment by miktuy** [comment]
Reproduced with Puppeteer 16.1.1 ((( `TypeError: els[0]._scrollIntoViewIfNeeded is not a function
                    at Puppeteer.scrollTo (/tests/node_modules/codeceptjs/lib/helper/Puppeteer.js:752:20)
                    at runMicrotasks (<anonymous>)
                    at processTicksAndRejections (node:internal/process/task_queues:96:5)
                    at async Object.setSliderWidthPercent (/tests/pages/pools/boosting.js:25:5)
                    at async Test.<anonymous> (/tests/tests/mobile/pools/boosting_test.js:27:5)`

**Comment by kobenguyent** [comment]
Please wait for the next release @miktuy. The patch is not yet released.
